# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/nbdev-strmlt-jptr-adhoc-example',
                'doc_host': 'https://ddobrinskiy.github.io',
                'git_url': 'https://github.com/ddobrinskiy/nbdev-strmlt-jptr-adhoc-example',
                'lib_path': 'src'},
  'syms': { 'src.app': {},
            'src.pages.DS-1': { 'src.pages.DS-1.get_data': ('ds-1.html#get_data', 'src/pages/DS-1.py'),
                                'src.pages.DS-1.get_resource': ('ds-1.html#get_resource', 'src/pages/DS-1.py')},
            'src.pages.DS-2': { 'src.pages.DS-2.get_data': ('ds-2.html#get_data', 'src/pages/DS-2.py'),
                                'src.pages.DS-2.get_resource': ('ds-2.html#get_resource', 'src/pages/DS-2.py')},
            'src.pages.quarterly_dashboard': { 'src.pages.quarterly_dashboard.get_data': ( 'quarterly dashboard.html#get_data',
                                                                                           'src/pages/quarterly_dashboard.py'),
                                               'src.pages.quarterly_dashboard.get_resource': ( 'quarterly dashboard.html#get_resource',
                                                                                               'src/pages/quarterly_dashboard.py')}}}
