# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/00-app.ipynb.

# %% auto 0
__all__ = []

# %% ../notebooks/00-app.ipynb 2
import streamlit as st

from streamlit_jupyter import StreamlitPatcher, tqdm

StreamlitPatcher().jupyter()  # register streamlit with jupyter-compatible wrappers


st.title("This is a demonstration of using streamlit for jupyter notebooks")

st.write("Every page can be a separate dashbord/adhoc ticket, or a part of a larger dashboard")
st.markdown("""
This will allow a team of data scientist to work in a single repo and:

- share code (this monorepo can also contain internal packages re-shared across projects)
- easily share their work with non-technical colleagues
- DRY (just write one single notebook, no need to port it to a dashboard)
- add sliders/filters to adhoc tickets, thus making them more interactive (non-tech colleagues can self-serve)

""")

# %% ../notebooks/00-app.ipynb 3
from pathlib import Path
cwd = Path.cwd()
if "notebooks" in cwd.name:
    path = cwd.parent/'src'/'pages'
else:
    path = cwd/'src'/'pages'

pagenames = sorted([f.name.split('.')[0] for f in path.glob("*.py") if not f.name.startswith("_")])

st.header("Table of contents:")
toc = ''
for page in pagenames:
    toc += f'- [{page}](./{page})\n'

st.markdown(toc)
